### PR TITLE
fix: handle invalid projectId

### LINKED ISSUE #19: fix: handle invalid projectId

### PR DESCRIPTION
**Pull request by chris13524**
# Description

Handles the project ID having invalid format instead of treating it as a error.

This helps eliminate 500 errors in the RPC proxy: https://walletconnect.slack.com/archives/C03SHRNSCBS/p1690466632022249

Resolves #19

## How Has This Been Tested?

Not tested

## Due Diligence

* [ ] Breaking change
* [ ] Requires a documentation update
* [ ] Requires a e2e/integration test update

### CODE REVIEW

**Review by heilhead — APPROVED** [review]

File: src/registry/client.rs [hunk 1]
```diff
@@ -90,22 +93,37 @@ impl RegistryHttpClient {
...
+
+fn is_hex_string(string: &str) -> bool {
+    string.chars().all(|c| c.is_ascii_hexdigit())
+}
+
 async fn parse_http_response(resp: reqwest::Response) -> RegistryResult<Option<ProjectData>> {
-    match resp.status().as_u16() {
-        200..=299 => Ok(Some(resp.json().await?)),
-        403 => Err(RegistryError::Config(INVALID_TOKEN_ERROR)),
-        404 => Ok(None),
```
Comment (arein) [inline src/registry/client.rs:108]: Can you add a 400 case here to return 400 to the caller as well?

**Review by arein — COMMENTED** [review]
Are there some tests that can be updated?

File: src/registry/client.rs (hunk 1 above)
Comment (chris13524) [reply src/registry/client.rs:108]: What do you mean? This is handled by the `_` case.

**Review by heilhead — APPROVED** [review]

**Review by arein — APPROVED** [review]
